formatter: "markdown table"

version: ">= 0.16.0"

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  {{ include "../../doc/INSTRUCTIONS.md" }}

  ## Examples
  ### AWS Route 53 Minimal Example
  This is the bare minimum configuration need to deploy a website using Route 53
  ```hcl
  {{ include "../../example-files/hcl/aws-minimal.tf" }}
  ```
  ### AWS Route 53 Example with a Custom Bucket Access Policy
  ```hcl
  {{ include "../../example-files/hcl/aws-bucket-access-policy.tf" }}
  ```
  ### AWS Route 53 Example with Bucket Lifecycle Policy and KMS Key for Encryption
  ```hcl
  {{ include "../../example-files/hcl/aws-bucket-lifecycle-and-kms-key.tf" }}
  ```

  ### AWS Route 53 Full Example
  Not every option is passed but this will provide an example of a full configuration.
  ```hcl
  {{ include "../../example-files/hcl/aws-full.tf" }}
  ```
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}


output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: false
  required: true
  sensitive: true
  type: true
