repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
    - id: terraform-docs-go
    - id: terraform-docs-go
      args: ["examples/aws-only"]
    - id: terraform-docs-go
      args: ["examples/gandi-livedns"]

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "v0.1.22"
    hooks:
    - id: terraform-fmt
      args: ['-recursive']
    - id: terraform-fmt
      args: ['examples/aws-only/.example.tf']
    - id: terraform-fmt
      args: ['examples/gandi-livedns/.example.tf']
    - id: terraform-validate
      exclude: 'example'

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.81.0" # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
    - id: terraform_tflint
      exclude: 'example'
      args:
      - --hook-config=--delegate-chdir

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: detect-aws-credentials
